<div class="span4 offset4">
	<form method="POST" action="" class="form-horizontal">
		<input type="hidden" name="steps[]" value="1"/>
		<div class="control-group">
			<legend>App information</legend>
			<label class="control-label">Required IP</label>
			<div class="controls"><span class="uneditable-input"><?=$_SERVER['SERVER_ADDR']?></span></div>
		</div>
		<div class="control-group">
			<label class="control-label" for="app">App name</label>
			<div class="controls">
				<div class="input-prepend input-append">
					<span class="add-on">http://</span>		
					<input type="text" style="width: 75px" name="app" id="app" value="<?=$this->_app?>" autofocus="autofocus" placeholder="&lt;appname&gt;"/>
					<span class="add-on">.carerix.net/</span>
				</div>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" for="password">XML Password</label>
			<div class="controls"><input type="password" name="password" id="password" value="<?=$this->_password?>"/></div>
		</div>
		<div class="control-group">
			<div class="controls">
				<button type="reset" class="btn">Reset</button>
				&nbsp;
				<button type="submit" class="btn btn-primary">Next</button>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label">Or</label>
			<div class="controls">
				<a href="upload" class="control-label btn btn-warning" style="width: auto;">Upload new CSV</a>
			</div>
		</div>
	</form>
	
</div>