<form method="POST" action="">
	<table>
		<tr>
			<td>Required IP is:</td>
			<td><?=$_SERVER['SERVER_ADDR']?></td>
		</tr>
		<tr>
			<td>App:</td>
			<td><?=$this->_app?></td>
		</tr>
		<tr>
			<td>Password:</td>
			<td>*****</td>
		</tr>
		<tr>
			<td>From language:</td>
			<td>
				<select name="sourcelanguage">
<?php
	foreach ( $languages as $lang ) {
		$selected = $this->_sourcelanguage === $lang ? ' selected="selected"' : '';
		echo "<option value='{$lang}'{$selected}>{$lang}</option>\n";
	}
?>
				</select>
			</td>
		</tr>
		<tr>
			<td rowspan="<?=(count($languages) + 1)?>">To languages:</td>
<?php
	foreach ( $languages as $datanodeid => $lang ) {
		$checked = in_array($lang, $this->_filllanguages) ? ' checked="checked"' : '';
		echo "<td><label><input type='checkbox' name='filllanguages[$datanodeid]' value='{$lang}'{$checked}>{$lang}</label></td></tr>\n<tr>";
	}
?>		
			<td><b>Missing languages?</b> Check the translation file's header against the system languages available in the App
		</tr>
		<tr>
			<td>Miscellaneous:</td>
			<td>
				<input type="hidden" name="overwrite" value="0"/>
				<input type="checkbox" id="overwrite" name="overwrite" value="1"<?=$this->_overwrite?' checked="checked"':''?>/>
				<label for="overwrite">Overwrite already existing nodes</label>
			</td>
		</tr>
		<tr>
			<td><input name="password" value="Terug" type="submit"/></td>
			<td><input type="reset"/><input type="submit"/></td>
		</tr>
		
	</table>
</form>