<!DOCTYPE html>
<html>
<head>
<title>Translate your App!</title>
<base href="http://<?=$_SERVER['HTTP_HOST']?>/CxTranslateDataNodes/"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link rel="stylesheet" type="text/css" href="bootstrap.min.css"/>
<link rel="stylesheet" type="text/css" href="bootstrap-responsive.min.css"/>
</head>
<body>
<div class="container-fluid">
	<div class="row-fluid">&nbsp;</div>
	<div class="row-fluid">
		<?=ViewController::showView()?>
	</div>
</div>
</body>
</html>